### PR TITLE
add respectful function

### PR DESCRIPTION
**Pull request by minkiminki**
c.f. #11

### CODE REVIEW

**Comment by jeehoonkang** [comment]
@minkiminki Question: is it the same with [the implementation in promising-coq](https://github.com/snu-sf/promising-coq/blob/master/src/lib/respectful5.v)?  Or is there anything different from it?

I'd like to also ask how do you think of #20 by @Lysxia.

**Comment by minkiminki** [comment]
@jeehoonkang It's little bit different.
Following lines are added in the definition of `weak_respectful`.
https://github.com/snu-sf/paco/blob/804c5d49e476c00631c69b3d47e74c09ed58f1b0/src/paco3_respectful.v#L136-L140

However, this pull request can be applied to `promising-coq` without any modifying of code.

**Comment by minkiminki** [comment]
In order to reduce compilation time, I will replace the use of `eauto` tactics with concrete proofs and commit again.

**Comment by minkiminki** [comment]
(for #20) @Lysxia Do you mean that changing `pcofix`'s behaviour would be better for the users?

**Comment by Lysxia** [comment]
On 2/1/19 2:11 AM, Minki Cho wrote:
> (for #20 <https://github.com/snu-sf/paco/issues/20>) @Lysxia 
> <https://github.com/Lysxia> Do you mean that changing |pcofix|'s 
> behaviour would be better for the users?
That's right! Possibly even change the definition of `paco`, unless I'm 
missing something.

**Comment by gilhur** [comment]
@Lysxia It makes sense to change the definition of paco to include the greatest respectful closure. However I think it is also good to keep the official definition as simple as possible, so that one can easily trust the correctness of the definition. At least it is obvious that the current definition of paco with the bottom parameter is the greatest fixpoint by definition.

Anyway let's see how convenient the current version of paco is. If that change would simplify things greatly, I am happy to adopt the change.

**Pull request merged**
