### PR TITLE
define n-ary paco using 1-ary paco

### PR DESCRIPTION
**Pull request by minkiminki**
This pr reduces compilation time from 75 sec to 13 sec.

### CODE REVIEW

**Comment by jeehoonkang** [comment]
Thanks for the PR.  Probably @Lysxia will be also interested?

Related: #12

**Comment by jeehoonkang** [comment]
I think I couldn't quite get the idea here...  Shall we have an offline meeting tomorrow (Monday)?

**Comment by jeehoonkang** [comment]
I'm closing and re-opening it for triggering a Travis CI run.

**Comment by jeehoonkang** [comment]
CI test fails: https://travis-ci.org/snu-sf/paco/jobs/406835722#L697-L702

**Comment by minkiminki** [comment]
I fixed it!!

**Pull request merged**
